config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'

  get 'messages/new'

  get 'users/new'

  get '/login' => 'sessions#new'

  delete 'logout' => 'sessions#destroy'

  root 'home#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  resources :relationships

  post 'accept_request' => 'relationships#accept_request'

  get 'sent_messages' => 'messages#sent_messages'

  get 'inbox' => 'messages#received_messages'

  post 'block_user' => 'relationships#block_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: 'User'
	belongs_to :recepient, class_name: 'User'

	scope :unread, -> {where(read_at: nil)}

	validates :body, presence: true

	def mark_as_read!
		self.read_at = Time.now
		save!
	end

	def read?
		read_at
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user, class_name: 'User'
	belongs_to :target, class_name: 'User'

	validates :user_id, :presence => true, :uniqueness => {:scope => :target_id}
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :name, presence: true
	validates :email, uniqueness: true

	has_many :sent_messages, foreign_key: 'sender_id', class_name: 'Message'
	has_many :received_messages, foreign_key: 'recepient_id', class_name: 'Message'

	has_many :relationships, foreign_key: 'user_id', class_name: 'Relationship'
	has_many :request_relationships, foreign_key: 'target_id', class_name: 'Relationship'

	has_many :targets, through: :relationships
	has_many :request_targets, through: :request_relationships, source: :user

	scope :all_except, -> (user) { where.not(id: user) }
	has_many :friends, -> {where(relationships: {status: 'friend'})}, through: :relationships, source: :target

	def received_messages
		Message.where(recepient: self)
	end

	def sent_messages
		Message.where(sender: self)
	end

	def lastest_received_messages(n)
		received_messages.order(created_at: :desc).limit(n)
	end

	def unread_messages
		received_messages.unread
	end

	def get_relationship(user)
		if relationship = Relationship.where(target_id: user.id, user_id: id).take
			relationship.status
		end
	end	

	def send_friend_request(target_id)
		target = User.find(target_id)
		relationship = Relationship.new(user: self, target: target, status: "pending")
		self.relationships << relationship
	end

	def accept_friend_request(target_id)
		request = request_relationships.where(user_id: target_id).take
		request.status = "friend"
		request.save

		self.relationships << Relationship.new(user_id: id, target_id: target_id, status: "friend")
	end

	def all_friends

	end

	def gravatar
		"http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email.downcase)}"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
  	return @current_user if @current_user
  	if session[:user_id]
  		@current_user = User.find session[:user_id]
  	end
  end

  def logged_in?
  	if session[:user_id]
  		true
  	else
  		false
  	end
  end

  def require_login
  	unless logged_in?
  		flash[:notice] = "You must sign in to see this page!"
  		redirect_to login_path
  	end
  end

  def skip_if_logged_in
  	if logged_in?
  		redirect_to users_path
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  	@message = Message.new
  	unless @users = current_user.friends
		flash[:notice] = "You must have friends before send out message"
	end
  end

  def create
  	@message = Message.new(message_params)
  	if @message.save
  		flash[:success] = "Message sent!"
  		redirect_to root_path
  	else
  		flash[:error] = @message.errors.full_messages.to_sentence
  		@users = current_user.friends
  		render 'new'
  	end
  end

  def sent_messages
  	@messages = current_user.sent_messages
  end

  def received_messages
  	@messages = current_user.received_messages
  end

  def show 
  	@message = Message.find(params[:id])
  	unless @message.recepient_id = current_user.id
  		flash[:error] = "You are not allow to view this message"
  		redirect_to users_path
  	end
  	@is_read = @message.read?
  	@message.mark_as_read!
  end

  private

  def message_params
  	params.require(:message).permit(:sender_id, :recepient_id, :body)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	current_user.send_friend_request(params[:target_id])
  	redirect_to users_path
  end

  def accept_request
  	current_user.accept_friend_request(params[:target_id])
  	redirect_to users_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	if @user = User.find_by_email(params[:email])
  		if @user.authenticate params[:password]
  			session[:user_id] = @user.id
  			flash[:success] = "Logged in!"
  			redirect_to root_path
  		else
  			flash[:error] = "Wrong password!"
  			redirect_to 'new'
  		end
  	else
  		flash[:error] = "Cannot find user!"
  		redirect_to 'new'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	flash[:success] = "Logged out!"
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all_except(current_user)
	end

	def show 
		@users = User.all_except(current_user)
		render 'index'
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Account created!"
			redirect_to root_path
		else
			flash[:error] = "Error: #{@user.errors.full_messages.to_sentence}"
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end
	

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
		{ success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
	end

	def flash_messages(opts = {})
		flash.map do |msg_type, message|
			content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
				content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
			end
		end.join.html_safe
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def flash_class_name(key)
		case key.to_s
		when 'success'
			"alert-success"
		when 'error'
			"alert-danger"
		else
			"alert-warning"
		end
	end

	def relationship_button(user)
		case current_user.get_relationship user
		when "friend"
			button_to 'Block', block_user_path, params: {target_id: user.id}
		when "pending"
			content_tag(:div, "Request sent", class: 'btn btn-secondary')
		when "block"
			content_tag(:div, "Blocked!", class: 'btn btn-secondary')
		when nil
			if current_user.request_relationships.any? {|relationship| relationship.user_id == user.id}
				button_to "Accept friend request", accept_request_path, params: {target_id: user.id}
			else
				button_to "Add friend", relationships_path, params: { target_id: user.id }
			end
		else
			content_tag(:div, "nothing", class: 'btn btn-secondary')
		end	
	end
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>VICHAT</h1>
  <p>Chat application for Coderschool</p>
	<%= link_to "Register now", new_user_path, class: "btn btn-primary btn-lg" %>
	<%= link_to "Login", login_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Vichat</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<!--<% if current_user %>
	<div class="alert alert-info">
		Welcome, <%= current_user.name %>
	</div>
	<% end %>-->
	<nav class="navbar navbar-dark bg-inverse navbar-static-top">
		<a href="/" class="navbar-brand">ViChat</a>
		<ul class="nav navbar-nav">
			<% unless logged_in? %>
			<li class="nav-item">
				<%= link_to 'Log In', login_path, class: 'nav-link'%>
			</li>
			<li class="nav-item">
				<%= link_to 'Sign Up', new_user_path, class: 'nav-link'%>
			</li>
			<% else %>
			<li class="nav-item">
				<%= link_to current_user.name, users_path, class: 'nav-link' %>
			</li>
			<li class="nav-item">
				<%= link_to 'Log Out', logout_path, method: 'delete', class: 'nav-link'%>
			</li>
			<li class="nav-item">
			<%= link_to 'new message', new_message_path, class: 'nav-link' %>
			</li>
			<li class="nav-item">
			<%= link_to 'Sent messages', sent_messages_path, class: 'nav-link' %>
			</li>
			<li class="nav-item">
			<%= link_to 'Inbox', inbox_path, class: 'nav-link' %>
			</li>
			<% end %>
		</ul>
	</nav>
	<% if flash.any? %>
	<%= flash_messages %>
	<% end %>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/messages/new.html.erb
<%= form_for @message do |f| %>
	<%= f.hidden_field :sender_id, class: 'form-control', value: current_user.id %>
<div class="form-group">
	<%= f.label :recepient_id, class: 'form-control-label' %>
	<%= f.collection_select :recepient_id, @users, :id, :name, {:prompt => 'select recepient ...'},{:class => 'form-control'} %>
</div> 
<div class="form-group">
	<%= f.label :body, class: 'form-control-label' %>
	<%= f.text_area :body, class: 'form-control' %>
</div> 
<%= f.submit 'Send', class: 'btn btn-primary' %>
<% end %>

app/views/messages/received_messages.html.erb
<h1>Inbox</h1>
<ul class="list-group">
<% if !@messages.blank? %>
	<% @messages.each do |message| %>
		<li class="list-group-item">
			<%= link_to "Message sent from #{message.sender.name} at #{message.created_at.strftime("%B %d at %I:%M %p")}", message_path(message.id)%>
			<span class="pull-xs-right">
			<% if message.read? %>
			read at <%= time_ago_in_words message.read_at %> ago
			<% else %>
			unread
			<% end %>
			</span>
		</li>
	<% end %>
	<% end %>
</ul>

app/views/messages/sent_messages.html.erb
<h2>Sent messages</h2>
<ul class="list-group">
	<% @messages.each do |message| %>
		<li class="list-group-item">
			Message sent to <%= message.recepient.email%> at <%= message.created_at.strftime("%B %d at %I:%M %p")%>
			<span class="pull-xs-right">
			<% if message.read? %>
			read at <%= time_ago_in_words message.read_at %> ago
			<% else %>
			unread
			<% end %>
			</span>
		</li>
	<% end %>
</ul>

app/views/messages/show.html.erb
<% if @is_read %>
	<h1>Your message has been read! </h1>
<% else %>
	<h2 class="message-header">From: <%= "#{@message.sender.name} - #{@message.sender.email}"%></h2>
	<div class="message-body">
		<%= @message.body %>
	</div>
<% end %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/users/_user.html.erb
<div class="col-xs-12 col-md-4">
  <div class="card">
    <%= image_tag user.gravatar %>
    <div class="card-block">
      <h4 class="card-title"><%= user.try(:name) %></h4>
      <%= relationship_button(user) %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h2>User List</h2>
<% @users.in_groups_of 3 do |group| %>
<div class="row">
	<%= render partial: 'user', collection: group.compact %>	
</div>

<% end %>

app/views/users/new.html.erb
<h1>Create New Account</h1>

<%= form_for @user do |f| %>
<div class="form-group">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :email %>
	<%= f.text_field :email, class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :password %>
	<%= f.password_field :password, class: 'form-control' %>
</div>
<div class="form-group">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>
</div>
<%= f.submit 'Create', class: 'btn btn-secondary' %>
<% end %>